Update functionality_tests.yml

diff --git a/.github/workflows/functionality_tests.yml b/.github/workflows/functionality_tests.yml
--- a/.github/workflows/functionality_tests.yml
+++ b/.github/workflows/functionality_tests.yml
@@ -22,7 +22,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           python -m pip install -r requirements.txt
-      - name: Adding Subscription correctly
+      - name: Adding Subscription
         run: |
           python3 ./yt_manager.py add-subscription https://www.youtube.com/@PracticalEngineeringChannel
           EXIT_CODE=$?
@@ -35,9 +35,9 @@ jobs:
             exit 1
           fi
         shell: bash
-      - name: Adding Subscription wrong (missing link)
+      - name: List Subscriptions
         run: |
-          python3 ./yt_manager.py add-subscription
+          python3 ./yt_manager.py list-subscription
           EXIT_CODE=$?
           if [ $EXIT_CODE -eq 0 ]; then
             echo "Command succeeded with exit code 0"
@@ -48,4 +48,19 @@ jobs:
             exit 1
           fi
         shell: bash
+      - name: Delete Subscription
+        run: |
+          python3 ./yt_manager.py del-subscription @PracticalEngineeringChannel
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -eq 0 ]; then
+            echo "Command succeeded with exit code 0"
+          elif [ $EXIT_CODE -eq -1 ]; then
+            echo "Command failed with exit code -1"
+          else
+            echo "Command exited with unexpected code $EXIT_CODE"
+            exit 1
+          fi
+        shell: bash
+      
+      
     
